name: ruff & mypy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3

      - name: Install Python (3.11)
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: 3.11

      - name: Install the project
        run: uv sync --all-extras --dev --no-install-project

      - name: Ruff check
        run: uv run ruff check --diff

      - name: Ruff format
        run: uv run ruff format --diff

      - name: Mypy
        run: uv run mypy .
